trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch

pool:
  name: dwipool
  demands:
    - agent.name -equals terraformagent

variables:
  terraformVersion: '1.3.7'  # Terraform version
  backendResourceGroup: 'rg-tf-backend'  # Azure Resource Group where the storage account exists
  backendStorageAccount: 'rgbackendstor'  # Your Azure Storage Account
  backendContainer: 'tfstate'  # The container name where the state files will be stored

parameters:
  - name: environment
    type: string
    displayName: 'Select Environment'
    values:
      - dev
      - prod
    default: 'dev'
